[app_fri_params.fri_params]
log_blowup = 1
log_final_poly_len = 0
num_queries = 100
proof_of_work_bits = 16

[leaf_fri_params.fri_params]
log_blowup = 1
log_final_poly_len = 0
num_queries = 100
proof_of_work_bits = 16

[app_vm_config.rv32i]

[app_vm_config.rv32m]

[app_vm_config.io]

[app_vm_config.keccak]

[app_vm_config.castf]

[app_vm_config.modular]
supported_modulus = ["52435875175126190479447740508185965837690552500527637822603658699938581184513"]

[app_vm_config.native]
